# Generated by Django 5.0.2 on 2024-04-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_WSI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_name", models.CharField(max_length=250)),
                ("slide_number", models.CharField(max_length=250)),
                ("magnification_level", models.CharField(max_length=250)),
                ("wsi_patches_folder", models.ImageField(upload_to="wsi_patches/")),
            ],
        ),
    ]
