# Generated by Django 5.0.2 on 2024-04-14 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0003_add_wsi_table_delete_add_wsi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_wsi_table",
            name="wsi_patches_folder",
        ),
        migrations.AddField(
            model_name="add_wsi_table",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="add_wsi_table",
            name="zip_file",
            field=models.FileField(null=True, upload_to="addWSI_zipfiles/"),
        ),
    ]
