# Generated by Django 5.0.2 on 2024-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0004_remove_add_wsi_table_wsi_patches_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_wsi_table",
            name="zip_file",
            field=models.FileField(upload_to="addWSI_zipfiles/"),
        ),
    ]
