# Generated by Django 5.0.2 on 2024-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0005_alter_add_wsi_table_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_wsi_table",
            name="zip_file",
            field=models.FileField(upload_to="WSI_zipfiles/"),
        ),
    ]
