# Generated by Django 5.0.2 on 2024-04-19 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0006_alter_add_wsi_table_zip_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_IHC_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=250)),
                ("stain_type_IHC", models.CharField(max_length=250)),
                ("zip_file", models.FileField(upload_to="IHC_files/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
