# Generated by Django 5.0.2 on 2024-04-20 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appforsegppt1", "0007_add_ihc_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_HandE_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=250)),
                ("zip_file", models.FileField(upload_to="HandE_files/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="add_tumorMask_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mask_name", models.CharField(max_length=250)),
                ("corres_slide_name", models.CharField(max_length=250)),
                ("corres_slide_number", models.CharField(max_length=250)),
                ("zip_file", models.FileField(upload_to="tumorMask_files/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
