# Generated by Django 2.2.28 on 2024-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforsegppt1', '0010_imagepatch_slideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='original_filename',
            field=models.CharField(help_text='The original file name of the uploaded image.', max_length=255, null=True),
        ),
    ]
