# Generated by Django 2.2.28 on 2024-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforsegppt1', '0011_slideimage_original_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='slideimage',
            name='slide_number',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename of the uploaded image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the slide.'),
        ),
    ]
