# Generated by Django 2.2.28 on 2024-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforsegppt1', '0012_auto_20240421_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='filename',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='slide_number',
            field=models.CharField(blank=True, default='default_value', help_text='An optional identifier or number associated with the slide.', max_length=50),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the slide, including any relevant clinical or contextual information.'),
        ),
    ]
