# Generated by Django 2.2.28 on 2024-04-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforsegppt1', '0013_auto_20240421_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
