# Generated by Django 2.2.28 on 2024-04-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforsegppt1', '0014_slideimage_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepatch',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the slide.'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='slide_number',
            field=models.CharField(blank=True, help_text='An optional identifier or number associated with the slide.', max_length=500),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='title',
            field=models.CharField(help_text='A descriptive title for the slide.', max_length=500),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
